### PR TITLE
Update QuickBooksFacade.php

### PR DESCRIPTION
**Pull request by raymondjclark**
These changes address issue #46 items.

### CODE REVIEW

**Comment by raymondjclark** [comment]
This change must be done in conjunction with update to Plugin.php to process invoices before payments.

**Comment by keksa** [comment]
@raymondjclark The payment ordering is still some time away, but the plugin can easily work around this by sorting the retrieved payments array manually.
Something like this would work
```php
$ucrmPayments = $this->ucrmApi->query('payments?direction=ASC');
usort(
    $ucrmPayments,
    function (array $a, array $b) {
        return $a['id'] <=> $b['id'];
    }
);
foreach ($ucrmPayments as $ucrmPayment) {
	// ...
}

**Comment by keksa** [comment]
@raymondjclark Also, what do you mean by "update to Plugin.php"?

**Comment by raymondjclark** [comment]
I submitted an update to Plugin.php to reorder export of payments after invoices since we cannot post a payment to an invoice if the invoices are not exported first.

**Pull request merged**
