### PR TITLE
Refactoring and Option to Create leads

### PR DESCRIPTION
**Pull request by charuwts**
Updated config to have option to create lead instead of client and began refactoring code to use tests. Side note, does the file upload option have a public accessible URL? I wasn't able to get it to work with the logo.

### CODE REVIEW

**Comment by charuwts** [comment]
note: country/state selection introduced a bug, working on it

**Comment by charuwts** [comment]
Requesting review. (: @keksa @janprochazkacz

**Comment by keksa** [comment]
@charuwts will take a look into it soon, both me and @janprochazkacz were on holiday :)

Ad the publicly accessible file, no it does not have public URL, but it's an interesting point, could you please create feature request for that in https://community.ubnt.com/t5/UCRM-Feature-Requests/idb-p/UCRM-Ideas so that we don't lose it? I think this could be useful.
You can workaround this for now by using base64 encoding, take a look for example at https://stackoverflow.com/questions/3967515/how-to-convert-an-image-to-base64-encoding - note that it increases the size by around 30 % and can crash on memory if the image is too large though.

**Comment by charuwts** [comment]
Thank you @keksa hope you had a great holiday!

I will submit that feature request. +1:

**Comment by UBNT-Petr** [comment]
@charuwts what about to postpone the merging until the UCRM v2.13 becomes stable (late August). "Beta users" can always use the plugin from this branch while the "standard users" not using UCRM beta version are not affected.

**Comment by charuwts** [comment]
sounds good @UBNT-Petr

**Pull request merged**
